### ISSUE TITLE
Add Functionality to the progress bar

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/MemeFinder#1]

**Comment by soumam007** [comment]
I wish to work on this and if possible please add few description for help like ---->>>the mode  of the progress bar, if it will be determinate or indeterminate and how shall i proceed means what shall I take the maximum range of the progress bar(whether in total bytes of the memeList or in the sense of total no. of images in the memeList )

**Comment by Aniq55** [comment]
Keep the total number of matched images as the MAX.
```
Next: increase counter
Prev: decrease counter
```
