### ISSUE TITLE
Tiles view in GUI

### ISSUE THREAD

**Issue by ananyo2012** [NITDgpOS/MemeFinder#11]
It will be good to have a tiles mode in gui. This is pretty good if there are a lot of images. You can also keep a check box type select option in the tiles for deleting the images so that user can keep the images he/she wants and delete the rest images.

**Comment by Aniq55** [comment]
Similar to instagram

**Comment by soumam007** [comment]
@Aniq55  Its good to see that in the form of an instagram but when i am trying to display the 2nd image , 3rd image and so on by shifting it few pixels to the right of the previous pic . the whole canvas is getting refreshed and only the last picture is remaining
What shall i do ? any suggestions @ananyo2012 @Aniq55

**Comment by Aniq55** [comment]
Create 9 separate canvas (3X3) and shift the rows upwards/downwards as one scrolls down/up respectively.
