### ISSUE TITLE
Navigation of previous and next images using keyboards

### ISSUE THREAD

**Issue by soumam007** [NITDgpOS/MemeFinder#16]
I think we can use "bind" 
`frame.bind("<Key>", event_call)`

Actually I am having hard time to decipher the code :( 
Hope I will be able to work on it

**Comment by ZER-0-NE** [comment]
In addition to this, I believe a counter showing the number of memes for each search query can be beneficial.

**Comment by Aniq55** [comment]
@ZER-0-NE can you please open a new issue for that? I am closing this one for now, because some major design changes are underway.
