### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/MemeFinder#27]

**Comment by Deathrow77** [comment]
I am interested to work to work on this issue. Which CI server has to be used?

I think Travis CI is a good option.

**Comment by Aniq55** [comment]
@Deathrow77 sure, go ahead!

**Comment by Aniq55** [comment]
@Deathrow77 any progress on this?

**Comment by vixrant** [comment]
@Aniq55 Sure! Oh and set up a heroku dyno for the project!

**Comment by Aniq55** [comment]
@vixrant should it be a separate issue? If yes, please make one.

**Comment by vixrant** [comment]
> @vixrant should it be a separate issue? If yes, please make one.

Not really since it's not related to the source code per say... It's just a matter of deployment :p

**Comment by jayvasantjv** [comment]
Is this issue already been assigned?, Otherwise I would like to work upon this.

**Comment by Aniq55** [comment]
@jayvasantjv go ahead. I haven't seen any activity on this issue in the past week.

**Comment by jayvasantjv** [comment]
Okay @Aniq55
