### ISSUE TITLE
Create a webapp for MemeFinder

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/MemeFinder#3]
Use Flask

**Comment by soumam007** [comment]
I want to work on this

**Comment by shubhangsati** [comment]
Hi! I wish to work on this

**Comment by soumam007** [comment]
@shubhangsati  Sure you may proceed , actually at present I am not working in this issue :)

**Comment by vixrant** [comment]
Hi, would Django work?

**Comment by Aniq55** [comment]
@vixrant yes, Django is good enough. Go ahead!
