### ISSUE TITLE
Remove dependancy on shell scripts

### ISSUE THREAD

**Issue by Compro-Prasad** [NITDgpOS/MemeFinder#34]
Running a python program is as easy as running a shell script. So, it is better to use imports and call functions to keep the dependencies as less as possible. Spawning a process takes time and memory which isn't a positive point for a search engine.

The `run.sh` might be necessary for easy interaction for a new user. So, it can be kept as it is.

**Comment by vixrant** [comment]
This can be solved with a single python file like I mentioned in #33.
