### ISSUE TITLE
Migrate data to a database

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/MemeFinder#6]
Currently all the data is stored in text files and read from it. Use a database (preferably MongoDB) to store data and do the following
* migrate the current data in txt file to that
* make code changes to read/write the database and not txt file in the future

**Comment by ananyo2012** [comment]
Idk if you are intending to use this for some data analysis or just as an image finder, you can perhaps use csv files. The python csv library has pretty good reader,  writer methods. Or best if you use SciPy libraries like numpy.

**Comment by Nairit11** [comment]
So are we supposed to migrate to mongoDB or create csv files and use pandas and numpy?

**Comment by jayvasantjv** [comment]
Hi, I would like to work upon this.

**Comment by Aniq55** [comment]
@jayvasantjv sure, go ahead. Do you have any questions?

**Comment by jayvasantjv** [comment]
None as of now, ll ping on Gitter channel if I get any. Thanks!

**Comment by Aniq55** [comment]
@vixrant are you using CSV files still, or have moved to use a database?

**Comment by vixrant** [comment]
I haven't changed the database. I'll leave that for others to do :p
